apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-stack-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gluster-k3s/prometheus-stack"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-stack-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi