apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-stack-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gluster-k3s/prometheus-stack"